// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[LEFT_BRACKET-5]
	_ = x[RIGHT_BRACKET-6]
	_ = x[COMMA-7]
	_ = x[COLON-8]
	_ = x[DOT-9]
	_ = x[PLUS-10]
	_ = x[SEMICOLON-11]
	_ = x[SLASH-12]
	_ = x[STAR-13]
	_ = x[BANG-14]
	_ = x[BANG_EQUAL-15]
	_ = x[EQUAL-16]
	_ = x[EQUAL_EQUAL-17]
	_ = x[GREATER-18]
	_ = x[GREATER_EQUAL-19]
	_ = x[LESS-20]
	_ = x[LESS_EQUAL-21]
	_ = x[MINUS-22]
	_ = x[MINUS_GREATER-23]
	_ = x[IDENTIFIER-24]
	_ = x[STRING-25]
	_ = x[NUMBER-26]
	_ = x[LET-27]
	_ = x[AND-28]
	_ = x[OR-29]
	_ = x[ELSE-30]
	_ = x[FALSE-31]
	_ = x[FN-32]
	_ = x[FOR-33]
	_ = x[IF-34]
	_ = x[NIL-35]
	_ = x[RETURN-36]
	_ = x[SUPER-37]
	_ = x[TRUE-38]
	_ = x[WHILE-39]
	_ = x[BREAK-40]
	_ = x[CONTINUE-41]
	_ = x[EOF-42]
}

const _TokenType_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACELEFT_BRACKETRIGHT_BRACKETCOMMACOLONDOTPLUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALMINUSMINUS_GREATERIDENTIFIERSTRINGNUMBERLETANDORELSEFALSEFNFORIFNILRETURNSUPERTRUEWHILEBREAKCONTINUEEOF"

var _TokenType_index = [...]uint16{0, 10, 21, 31, 42, 54, 67, 72, 77, 80, 84, 93, 98, 102, 106, 116, 121, 132, 139, 152, 156, 166, 171, 184, 194, 200, 206, 209, 212, 214, 218, 223, 225, 228, 230, 233, 239, 244, 248, 253, 258, 266, 269}

func (i TokenType) String() string {
	i -= 1
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
