// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[LEFT_BRACKET-5]
	_ = x[RIGHT_BRACKET-6]
	_ = x[COMMA-7]
	_ = x[COLON-8]
	_ = x[DOT-9]
	_ = x[PLUS-10]
	_ = x[MINUS-11]
	_ = x[SEMICOLON-12]
	_ = x[SLASH-13]
	_ = x[STAR-14]
	_ = x[BANG-15]
	_ = x[BANG_EQUAL-16]
	_ = x[EQUAL-17]
	_ = x[EQUAL_EQUAL-18]
	_ = x[GREATER-19]
	_ = x[GREATER_EQUAL-20]
	_ = x[LESS-21]
	_ = x[LESS_EQUAL-22]
	_ = x[IDENTIFIER-23]
	_ = x[STRING-24]
	_ = x[NUMBER-25]
	_ = x[LET-26]
	_ = x[AND-27]
	_ = x[OR-28]
	_ = x[ELSE-29]
	_ = x[FALSE-30]
	_ = x[FN-31]
	_ = x[FOR-32]
	_ = x[IF-33]
	_ = x[NIL-34]
	_ = x[RETURN-35]
	_ = x[SUPER-36]
	_ = x[TRUE-37]
	_ = x[WHILE-38]
	_ = x[BREAK-39]
	_ = x[CONTINUE-40]
	_ = x[EOF-41]
}

const _TokenType_name = "LEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACELEFT_BRACKETRIGHT_BRACKETCOMMACOLONDOTPLUSMINUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERLETANDORELSEFALSEFNFORIFNILRETURNSUPERTRUEWHILEBREAKCONTINUEEOF"

var _TokenType_index = [...]uint16{0, 10, 21, 31, 42, 54, 67, 72, 77, 80, 84, 89, 98, 103, 107, 111, 121, 126, 137, 144, 157, 161, 171, 181, 187, 193, 196, 199, 201, 205, 210, 212, 215, 217, 220, 226, 231, 235, 240, 245, 253, 256}

func (i TokenType) String() string {
	i -= 1
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
